---
title: "Academic Service"
author: "Bastián González-Bustamante"
date: "12-12-2019"
output: html_document
---

**Supervisor and Examiner**

* BA Dissertations Supervisor and Examiner
  + BA in Public Administration, Universidad de Santiago, 2014-2019.
* MA Dissertations Examiner
  + MA in Political Science, Universidad de Chile, 2018-2019.
  + MA in Public Management, Universidad de Santiago, 2018.
* Internship Supervisor
  + BA in Public Administration, Universidad de Santiago, 2018-2019.
  + Student Exchange Programme, Wake Forest University, 2015.
  + Student Exchange Programme, American University, 2015.

**Peer Reviewer and Expert**

* Varieties of Democracy Project, University of Gothenburg, Sweden 2014, 2018-2020.
* Sectoral Commission for Research, Universidad de la República, Uruguay 2016, 2018.
* Times Higher Education World University Rankings, Elsevier, 2018.
* WoS & Scopus Journals (since 2013): 
  + *Colombia Internacional*; *Comunicación y Sociedad*; *Cuadernos.info*; *Cultura*, *Hombre y Sociedad*; *ERLACS*; *Gestión y Política Pública*; *Historia*; *International Review of Administrative Sciences*; *Latin American Politics and Society*; *Latin American Research Review*; *Revista de Ciencia Política*; *Revista de Estudios Sociales*; *Revista de Gestión Pública*; *Revista de Sociologia e Política*; *RMCPyS*.
* SciELO & Latindex Journals (since 2013): 
  + *Cuadernos FHyCS-UNJu*; *DAAPGE*; *Estado, Gobierno y Gestión Pública*; *e-Ciencias de la Información*; *Polis, Revista Latinoamericana*; *Política, Revista de Ciencia Política*; *Revista Chilena de Derecho y Ciencia Política*; *Vía Iuris*.
