---
title: 'Changelog'
subtitle: 'Chilean Political Science Impact Ranking'
weight: 5
date: '2019-12-01'
authors: ["bgonzalezbustamante"]
summary: 'See changes to this project'
---

All notable changes to this project will be documented in this section: <i class="fas fa-plus-circle"></i> Added <i class="fas fa-exchange-alt"></i> Changed <i class="fas fa-minus-circle"></i> Deprecated <i class="fas fa-trash-alt"></i> Removed <i class="fas fa-wrench"></i> Fixed.

## [Unreleased]

### [2.7.5] - 2020-09-05
- <i class="fas fa-plus-circle"></i> Release of dataset (DOI: [10.17605/OSF.IO/M3NZD](http://doi.org/10.17605/OSF.IO/M3NZD)).
- <i class="fas fa-plus-circle"></i> Updated version impact ranking.
- <i class="fas fa-plus-circle"></i> Updated analysis career trajectories.
- <i class="fas fa-plus-circle"></i> Updated co-author network analysis.
- <i class="fas fa-plus-circle"></i> Updated version institutions ranking.
- <i class="fas fa-plus-circle"></i> Updated prediction of H-Index.
- <i class="fas fa-plus-circle"></i> Impact ranking weighted by journal publications.
- <i class="fas fa-exchange-alt"></i> Update of badges.

### [2.6.5] - 2020-06-05
- <i class="fas fa-plus-circle"></i> Release of dataset (DOI: [10.17605/OSF.IO/M3NZD](http://doi.org/10.17605/OSF.IO/M3NZD)).
- <i class="fas fa-plus-circle"></i> Updated version impact ranking.
- <i class="fas fa-plus-circle"></i> Updated analysis career trajectories.
- <i class="fas fa-plus-circle"></i> Updated co-author network analysis.
- <i class="fas fa-plus-circle"></i> Updated version institutions ranking.
- <i class="fas fa-plus-circle"></i> Prediction of H-Index.
- <i class="fas fa-plus-circle"></i> Validation code at GitHub repository.
- <i class="fas fa-exchange-alt"></i> Update of badges.

## [Released]

### [2.5.5] - 2020-03-14
- <i class="fas fa-plus-circle"></i> Chilean institutions ranking.
### Changed
- <i class="fas fa-exchange-alt"></i> Update of badges.
- <i class="fas fa-exchange-alt"></i> Minor typesetting corrections in the changelog.

### [2.4.5] - 2020-03-11
- <i class="fas fa-exchange-alt"></i> Minor typesetting corrections in the changelog.

### [2.4.4] - 2020-03-09
- <i class="fas fa-exchange-alt"></i> Update of researchers to be added.

### [2.4.3] - 2020-03-07
- <i class="fas fa-exchange-alt"></i> Update of researchers to be added.

### [2.4.2] - 2020-03-05
- <i class="fas fa-plus-circle"></i> Release of dataset (DOI: [10.17605/OSF.IO/M3NZD](http://doi.org/10.17605/OSF.IO/M3NZD)).
- <i class="fas fa-plus-circle"></i> Updated version impact ranking.
- <i class="fas fa-plus-circle"></i> Updated analysis career trajectories.
- <i class="fas fa-plus-circle"></i> Updated co-author network analysis.
- <i class="fas fa-exchange-alt"></i> Update of badges.

### [2.3.2] - 2020-02-11
- <i class="fas fa-exchange-alt"></i> Update of badges.

### [2.3.1] - 2020-02-04
- <i class="fas fa-plus-circle"></i> Changelog in TXT format at GitHub repository.
- <i class="fas fa-exchange-alt"></i> Revision of upgrade versioning.

### [2.2.1] - 2020-01-26
- <i class="fas fa-exchange-alt"></i> Update of badges at GitHub repository.
- <i class="fas fa-exchange-alt"></i> Update of researchers to be added.

### [2.2.0] - 2020-01-17
- <i class="fas fa-plus-circle"></i> License CC-BY Attribution 4.0 International at GitHub repository.

### [2.1.0] - 2020-01-14
- <i class="fas fa-plus-circle"></i> Shields.io badges in SVG.
- <i class="fas fa-exchange-alt"></i> Update of researchers to be added.

### [2.0.0] - 2020-01-05
- <i class="fas fa-plus-circle"></i> Integration between websites.
- <i class="fas fa-exchange-alt"></i> URL redirections.
- <i class="fas fa-trash-alt"></i> Previous CPS-Ranking website.

### [1.1.2] - 2020-01-02
- <i class="fas fa-plus-circle"></i> Preparing integration between the CPS-Ranking website and personal site at the University of Oxford.
- <i class="fas fa-minus-circle"></i> CPS-Ranking website.

### [1.0.2] - 2020-01-01
- <i class="fas fa-exchange-alt"></i> Minor typesetting corrections.

### [1.0.1] - 2019-12-23
- <i class="fas fa-exchange-alt"></i> Update of researchers to be added.

### [1.0.0] - 2019-12-16
- <i class="fas fa-plus-circle"></i> Upload of CPS-Ranking website.
- <i class="fas fa-exchange-alt"></i> URL redirections.
- <i class="fas fa-trash-alt"></i> R Markdown HTML presentations.

### [0.4.2] - 2019-12-10
- <i class="fas fa-exchange-alt"></i> Update of researchers to be added.

### [0.4.1] - 2019-12-05
- <i class="fas fa-plus-circle"></i> Model of CPS-Ranking website powered by R and the package blogdown.
- <i class="fas fa-minus-circle"></i> R Markdown HTML presentations.

### [0.3.1] - 2019-12-04
- <i class="fas fa-exchange-alt"></i> Adjust of co-author network algorithm.
- <i class="fas fa-exchange-alt"></i> Automation of analysis code.

### [0.3.0] - 2019-12-03
- <i class="fas fa-plus-circle"></i> Release of dataset (DOI: [10.17605/OSF.IO/M3NZD](http://doi.org/10.17605/OSF.IO/M3NZD)).
- <i class="fas fa-plus-circle"></i> Analysis of career trajectories.
- <i class="fas fa-plus-circle"></i> Co-author network analysis.

### [0.2.0] - 2019-12-02
- <i class="fas fa-plus-circle"></i> OSF project (DOI: [10.17605/OSF.IO/C8PRA](http://doi.org/10.17605/OSF.IO/C8PRA)).
- <i class="fas fa-plus-circle"></i> OSF data component (DOI: [10.17605/OSF.IO/M3NZD](http://doi.org/10.17605/OSF.IO/M3NZD)).
- <i class="fas fa-plus-circle"></i> Scraper code.
- <i class="fas fa-plus-circle"></i> Scrape Google Scholar data.
- <i class="fas fa-plus-circle"></i> Impact ranking.
- <i class="fas fa-plus-circle"></i> R Markdown HTML presentations.
- <i class="fas fa-plus-circle"></i> Researchers to be added.
- <i class="fas fa-wrench"></i> Tie in H-Index.

### [0.1.0] - 2019-12-01
- <i class="fas fa-plus-circle"></i> Sampling procedure.
